In [1]:
# import libaries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
movie_data = pd.read_csv("movies_data.csv")

In [3]:
movie_data

,Name,Year,Duration,Genre,Votes,Director,Actor 1,Actor 2,Actor 3,num_critic_for_reviews,director_facebook_likes,actor_1_facebook_likes,num_voted_users,cast_total_facebook_likes,num_user_for_reviews,actor_2_facebook_likes,movie_facebook_likes,Revenue_Millions,Rating
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,813.0,22000.0,27000.0,1144337.0,106759.0,2701.0,23000.0,164000.0,333.13,7.0
1,#Yaaram,2019,110,"Comedy, Romance",35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,462.0,475.0,640.0,212204.0,1873.0,738.0,632.0,24000.0,126.46,4.4
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,324.0,15.0,799.0,294810.0,2036.0,387.0,553.0,29000.0,138.12,4.7
3,...Yahaan,2005,142,"Drama, Romance, War",1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,375.0,282.0,25000.0,321795.0,58753.0,973.0,11000.0,10000.0,270.32,7.4
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,313.0,563.0,40000.0,522040.0,48486.0,1832.0,5000.0,5000.0,325.02,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5654,Zubaan,2015,115,Drama,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.1
5655,Zubeidaa,2001,153,"Biography, Drama, History",1496,Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.2
5656,Zulm Ki Zanjeer,1989,125,"Action, Crime, Drama",44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.8
5657,Zulmi,1999,129,"Action, Drama",655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
5658,Zulm-O-Sitam,1998,130,"Action, Drama",20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.2

In [4]:
#to see the top 5 entries
movie_data.head()

,Name,Year,Duration,Genre,Votes,Director,Actor 1,Actor 2,Actor 3,num_critic_for_reviews,director_facebook_likes,actor_1_facebook_likes,num_voted_users,cast_total_facebook_likes,num_user_for_reviews,actor_2_facebook_likes,movie_facebook_likes,Revenue_Millions,Rating
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,813.0,22000.0,27000.0,1144337.0,106759.0,2701.0,23000.0,164000.0,333.13,7.0
1,#Yaaram,2019,110,"Comedy, Romance",35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,462.0,475.0,640.0,212204.0,1873.0,738.0,632.0,24000.0,126.46,4.4
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,324.0,15.0,799.0,294810.0,2036.0,387.0,553.0,29000.0,138.12,4.7
3,...Yahaan,2005,142,"Drama, Romance, War",1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,375.0,282.0,25000.0,321795.0,58753.0,973.0,11000.0,10000.0,270.32,7.4
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,313.0,563.0,40000.0,522040.0,48486.0,1832.0,5000.0,5000.0,325.02,5.6

In [5]:
#shows the count of valid entries
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5659 entries, 0 to 5658
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       5659 non-null   object
 1   Year                       5659 non-null   int64
 2   Duration                   5659 non-null   int64
 3   Genre                      5659 non-null   object
 4   Votes                      5659 non-null   int64
 5   Director                   5659 non-null   object
 6   Actor 1                    5659 non-null   object
 7   Actor 2                    5659 non-null   object
 8   Actor 3                    5659 non-null   object
 9   num_critic_for_reviews     1990 non-null   float64
 10  director_facebook_likes    1990 non-null   float64
 11  actor_1_facebook_likes     1990 non-null   float64
 12  num_voted_users            1990 non-null   float64
 13  cast_total_facebook_likes  1990 non-null   float64
 14  num_user_for_reviews       1990 non-null   float64
 15  actor_2_facebook_likes     1990 non-null   float64
 16  movie_facebook_likes       1990 non-null   float64
 17  Revenue_Millions           872 non-null    float64
 18  Rating                     5659 non-null   float64
dtypes: float64(10), int64(3), object(6)
memory usage: 840.1+ KB

In [6]:
# Define columns to drop and ensure they exist
columns_to_drop = ['num_critic_for_reviews', 'director_facebook_likes',
                   'actor_3_facebook_likes', 'movie_facebook_likes', 'cast_total_facebook_likes']

# Filter columns that exist in the dataset
columns_to_drop = [col for col in columns_to_drop if col in movie_data.columns]

# Drop the columns
movie_data = movie_data.drop(columns=columns_to_drop)
print("Dropped columns:", columns_to_drop)

Dropped columns: ['num_critic_for_reviews', 'director_facebook_likes', 'movie_facebook_likes', 'cast_total_facebook_likes']

In [7]:
#shows the count of missing entries
movie_data.isnull().sum()

Name                         0
Year                         0
Duration                     0
Genre                        0
Votes                        0
Director                     0
Actor 1                      0
Actor 2                      0
Actor 3                      0
actor_1_facebook_likes    3669
num_voted_users           3669
num_user_for_reviews      3669
actor_2_facebook_likes    3669
Revenue_Millions          4787
Rating                       0
dtype: int64

In [8]:
# # Calculate the median of the 'num_critic_for_reviews' column
# num_critic_for_reviews_median = movie_data['num_critic_for_reviews'].median()
# # Replace missing values in the 'num_critic_for_reviews' column with the median
# movie_data['num_critic_for_reviews'] = movie_data['num_critic_for_reviews'].fillna(num_critic_for_reviews_median)

In [9]:
# # Calculate the median of the 'director_facebook_likes' column
# director_facebook_likes_median = movie_data['director_facebook_likes'].median()
# # Replace missing values in the 'director_facebook_likes' column with the median
# movie_data['director_facebook_likes'] = movie_data['director_facebook_likes'].fillna(director_facebook_likes_median)

In [10]:
# Calculate the median of the 'actor_1_facebook_likes' column
actor_1_facebook_likes_median = movie_data['actor_1_facebook_likes'].median()
# Replace missing values in the 'actor_1_facebook_likes' column with the median
movie_data['actor_1_facebook_likes'] = movie_data['actor_1_facebook_likes'].fillna(actor_1_facebook_likes_median)

In [11]:
# Calculate the median of the 'num_voted_users' column
num_voted_users_median = movie_data['num_voted_users'].median()
# Replace missing values in the 'num_voted_users' column with the median
movie_data['num_voted_users'] = movie_data['num_voted_users'].fillna(num_voted_users_median)

In [12]:
# # Calculate the median of the 'cast_total_facebook_likes' column
# cast_total_facebook_likes_median = movie_data['cast_total_facebook_likes'].median()
# # Replace missing values in the 'cast_total_facebook_likes' column with the median
# movie_data['cast_total_facebook_likes'] = movie_data['cast_total_facebook_likes'].fillna(cast_total_facebook_likes_median)

In [13]:
# Calculate the median of the 'num_user_for_reviews' column
num_user_for_reviews_median = movie_data['num_user_for_reviews'].median()
# Replace missing values in the 'num_user_for_reviews' column with the median
movie_data['num_user_for_reviews'] = movie_data['num_user_for_reviews'].fillna(num_user_for_reviews_median)

In [14]:
# Calculate the median of the 'actor_2_facebook_likes' column
actor_2_facebook_likes_median = movie_data['actor_2_facebook_likes'].median()
# Replace missing values in the 'actor_2_facebook_likes' column with the median
movie_data['actor_2_facebook_likes'] = movie_data['actor_2_facebook_likes'].fillna(actor_2_facebook_likes_median)

In [15]:
# # Calculate the median of the 'movie_facebook_likes' column
# movie_facebook_likes_median = movie_data['movie_facebook_likes'].median()
# # Replace missing values in the 'movie_facebook_likes' column with the median
# movie_data['movie_facebook_likes'] = movie_data['movie_facebook_likes'].fillna(movie_facebook_likes_median)

In [16]:
# Calculate the median of the 'Revenue_Millions' column
Revenue_Millions_median = movie_data['Revenue_Millions'].median()
# Replace missing values in the 'Revenue_Millions' column with the median
movie_data['Revenue_Millions'] = movie_data['Revenue_Millions'].fillna(Revenue_Millions_median)

In [17]:
movie_data.isnull().sum()

Name                      0
Year                      0
Duration                  0
Genre                     0
Votes                     0
Director                  0
Actor 1                   0
Actor 2                   0
Actor 3                   0
actor_1_facebook_likes    0
num_voted_users           0
num_user_for_reviews      0
actor_2_facebook_likes    0
Revenue_Millions          0
Rating                    0
dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

trans_data = movie_data.copy()
# Transform Director columns
trans_data['Name'] = labelencoder.fit_transform(movie_data['Name'])
trans_data['Director'] = labelencoder.fit_transform(movie_data['Director'])

# Transform Actors Columns
trans_data['Actor 1'] = labelencoder.fit_transform(movie_data['Actor 1'])
trans_data['Actor 2'] = labelencoder.fit_transform(movie_data['Actor 2'])
trans_data['Actor 3'] = labelencoder.fit_transform(movie_data['Actor 3'])
trans_data['Genre'] = labelencoder.fit_transform(movie_data['Genre'])


trans_data.head()

,Name,Year,Duration,Genre,Votes,Director,Actor 1,Actor 2,Actor 3,actor_1_facebook_likes,num_voted_users,num_user_for_reviews,actor_2_facebook_likes,Revenue_Millions,Rating
0,0,2019,109,229,8,629,1352,2272,319,27000.0,1144337.0,2701.0,23000.0,333.13,7.0
1,1,2019,110,184,35,1335,1198,719,2148,640.0,212204.0,738.0,632.0,126.46,4.4
2,3,1997,147,157,827,1530,378,75,2045,799.0,294810.0,387.0,553.0,138.12,4.7
3,4,2005,142,289,1086,2044,692,1112,2524,25000.0,321795.0,973.0,11000.0,270.32,7.4
4,76,2012,82,320,326,135,1934,1175,1013,40000.0,522040.0,1832.0,5000.0,325.02,5.6

In [19]:
# Import modeling Libraries
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [20]:
# Function of Multiple Linear Regression
def mlr(X, y):
    # Add a column of ones to X for the intercept term
    ones = np.ones((len(X),1))
    X = np.hstack((ones, X))

    # start to fomulateing with this formula : (X^T * X)^-1 * (X^T * y)

    # transpose of the X
    X_transpose = np.transpose(X)

    # X^T * X
    X_transpose_X = np.dot(X_transpose, X)

    # inverse of X^T * X
    X_transpose_X_inv = np.linalg.pinv(X_transpose_X)

    # then calculate the X^T * y
    X_transpose_y = np.dot(X_transpose, y)

    # Multiply the two term
    beta = np.dot(X_transpose_X_inv, X_transpose_y)

    return beta

# Function to predict using the fitted model
def predict_mlr(X, beta):

    # Step 1: Add a column of ones to X for the intercept term

    # Create a column of ones
    ones = np.ones((len(X), 1))
    X = np.hstack((ones, X))

    # Step 2: Compute predictions

     # Multiply X and beta
    y_pred = np.dot(X, beta)

    return y_pred

# Example dataset (features and target)
X = trans_data.drop(['Rating'],axis=1)
y = trans_data['Rating']


# Fit the MLR model
beta = mlr(X, y)
print("Coefficients (including intercept):", beta)

Coefficients (including intercept): [ 4.04284492e+01  1.33842465e-06 -1.72936913e-02 -4.20332953e-03
  1.36754486e-03  1.93967994e-05  4.93628634e-06  4.76559579e-05
  6.09680259e-05  7.27012150e-05 -4.33098332e-06 -6.46481663e-07
  2.37116461e-04 -1.27563929e-06  9.27837250e-04]

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [22]:
X_test = np.array(X_test)
y_pred = predict_mlr(X_test, beta)
y_pred

array([5.66146068, 5.83370102, 5.94969243, ..., 6.05987134, 6.12024741,
       5.42660522])

In [23]:
print('R2 score: ',r2_score(y_test,y_pred))
print('Mean squared error: ',mean_squared_error(y_test,y_pred))
print('Mean absolute error: ',mean_absolute_error(y_test,y_pred))

R2 score:  0.09061799762150313
Mean squared error:  1.6659267126223292
Mean absolute error:  1.032555433690832

In [53]:
from sklearn.ensemble import RandomForestRegressor
randregressor=RandomForestRegressor(n_estimators=50)
randregressor.fit(X_train,y_train)
predictions = randregressor.predict(X_test)
print('R2 score: ',r2_score(y_test,predictions))
print('Mean squared error: ',mean_squared_error(y_test,predictions))
print('Mean absolute error: ',mean_absolute_error(y_test,predictions))

R2 score:  0.3223428966226357
Mean squared error:  1.2414222709069493
Mean absolute error:  0.8430176678445229

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [57]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
X_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)
svr_rbf=SVR(kernel='rbf',C=100,gamma=0.001,epsilon=0.1)
#train the SVR model on training data
svr_rbf.fit(X_train_scaled,y_train)
#make predictions on test data
y_pred=(svr_rbf.predict(X_test_scaled))
#evaluate the model
mse=mean_squared_error(y_test,y_pred)

r2=r2_score(y_test,y_pred)
print('Mean absolute error: ',mean_absolute_error(y_test,y_pred))
print(f"mean squared error(MSE):{mse:.4f}") 
print(f"R^2 Score:{r2:4f}")

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Mean absolute error:  0.9788286436138433
mean squared error(MSE):1.5743
R^2 Score:0.140658

In [65]:
# Assuming the missing features are like 'movie_facebook_likes', 'num_critic_for_reviews', etc.
new_data = pd.DataFrame({
    'Name':['100% Love'],
    'Year': [2021],
    'Duration': [166],
    'Genre': ['Comedy, Drama, Romance'],
    'Votes': [63],
    'Director': ['Ram Gopal Varma'],
    'Actor 1': ['Mithun Chakraborty'],
    'Actor 2': ['Makrand Deshpande'],
    'Actor 3': ['Dalip Tahil'],
    'actor_1_facebook_likes': [40000],  # Fill with default value (e.g., 0)
    'num_voted_users': [306320],  # Add missing feature with default value
    'num_user_for_reviews': [736],  # Add missing feature with default value
    'actor_2_facebook_likes': [25000],  # Fill with default value (e.g., 0)
    'Revenue_Millions': [249.75]  # Fill with default value (e.g., 0)
    
})

# Transform categorical columns using the same labelEncoder
new_data['Name'] = labelencoder.fit_transform(new_data['Name'])
new_data['Director'] = labelencoder.fit_transform(new_data['Director'])
new_data['Actor 1'] = labelencoder.fit_transform(new_data['Actor 1'])
new_data['Actor 2'] = labelencoder.fit_transform(new_data['Actor 2'])
new_data['Actor 3'] = labelencoder.fit_transform(new_data['Actor 3'])

# Fix the Genre transformation (apply label encoder after transformation)
new_data['Genre'] = labelencoder.fit_transform(new_data['Genre'])

# Ensure the feature order matches the training data
new_data_transformed = new_data[[
     'Name','Year', 'Duration', 'Genre', 'Votes','Director',
    'Actor 1', 'Actor 2', 'Actor 3', 
    'actor_1_facebook_likes','num_voted_users',
     'num_user_for_reviews',
    'actor_2_facebook_likes',  
    'Revenue_Millions'
]]

# Predict ratings for the new data
predicted_ratings =randregressor.predict(new_data_transformed)

# Output predictions
print("Predicted Ratings:", predicted_ratings)

Predicted Ratings: [5.618]